import { prisma } from "@/lib/prisma";
import { executeChatCompletion } from "@/lib/llm-router";
import { writeVaultFile, ensureVaultExists } from "@/lib/vault";
import { slugify, formatResponseTime } from "@/lib/utils";
import { notifyWhatsAppUser } from "@/lib/whatsapp-service";


/** Calculate the next execution time for a routine */
export function calculateNextRun(
  type: string,
  timeStr?: string | null,
  scheduledAtStr?: Date | string | null
): Date | null {
  const now = new Date();

  if (type === "one_time") {
    if (!scheduledAtStr) return null;
    const target = new Date(scheduledAtStr);
    return isNaN(target.getTime()) ? null : target;
  }

  // Daily recurring routine
  if (type === "daily") {
    if (!timeStr) {
      timeStr = "09:00";
    }

    const [hoursStr, minsStr] = timeStr.split(":");
    const hours = parseInt(hoursStr || "9", 10);
    const mins = parseInt(minsStr || "0", 10);

    const next = new Date(now);
    next.setHours(hours, mins, 0, 0);

    // If time has already passed today, advance to tomorrow
    if (next.getTime() <= now.getTime()) {
      next.setDate(next.getDate() + 1);
    }

    return next;
  }

  return null;
}

/** Execute a routine: create Kanban task, run agent if autoExecute, save to Obsidian */
export async function executeRoutine(routineId: string) {
  const routine = await prisma.routine.findUnique({
    where: { id: routineId },
    include: { agent: true },
  });

  if (!routine) {
    throw new Error(`Routine ${routineId} not found`);
  }

  const agent = routine.agent;

  // 1. Create task on Kanban board
  const task = await prisma.task.create({
    data: {
      title: routine.title,
      description: routine.prompt,
      priority: routine.priority || "medium",
      status: routine.autoExecute ? "in_progress" : "backlog",
      agentId: agent?.id || null,
    },
    include: { agent: true },
  });

  await prisma.activityLog.create({
    data: {
      type: "routine_triggered",
      message: `Routine "${routine.title}" triggered task for ${agent ? agent.displayName : "Agent"}`,
      agentId: agent?.id || null,
    },
  });

  let executionResult = null;

  // 2. If autoExecute is enabled, run agent immediately
  if (routine.autoExecute) {
    const prompt = `You are executing an autonomous scheduled routine from Agent Studio OS.
ROUTINE: ${routine.title}
OBJECTIVE & INSTRUCTIONS:
${routine.prompt}

PRIORITY: ${routine.priority}
SCHEDULE TYPE: ${routine.type === "daily" ? `Daily at ${routine.time || "09:00"}` : "One-time Scheduled"}

Please execute this task with high quality:
- Provide an Executive Summary.
- Deliver clear, actionable deliverables or complete working code with explanation.
- Include structured findings, next steps, and obsidian wikilinks [[tasks]] or [[agents]] where relevant.`;

    executionResult = await executeChatCompletion({
      prompt,
      model: agent?.model || null,
      systemPrompt:
        agent?.systemPrompt ||
        "You are an autonomous AI specialist in Agent Studio OS executing a scheduled routine. Complete it with exceptional quality.",
      agentName: agent?.name,
    });

    // Update task to review with deliverable
    await prisma.task.update({
      where: { id: task.id },
      data: {
        status: "review",
        result: executionResult.content,
      },
    });

    // Save deliverable to shared Obsidian vault
    try {
      await ensureVaultExists();
      const filename = `tasks/${slugify(routine.title || "routine-task")}-${Date.now()}.md`;
      const vaultContent = `---
title: "${routine.title.replace(/"/g, '\\"')}"
routine_id: "${routine.id}"
status: "review"
priority: "${routine.priority}"
agent: "${agent ? agent.displayName : "Unassigned"}"
date: "${new Date().toISOString()}"
model: "${executionResult.modelUsed}"
latency: "${formatResponseTime(executionResult.latency)}"
tags:

  - routine
  - ${routine.type}
  - ${agent ? agent.name : "general"}
---

# ${routine.title}

> [!NOTE]
> Autonomous scheduled routine executed by **${agent ? agent.displayName : "Agent"}** on ${new Date().toLocaleString()}.

## Objective
${routine.prompt}

## Deliverable
${executionResult.content}

---
*Generated by Agent Studio OS Routine Engine*
`;
      await writeVaultFile(filename, vaultContent);
    } catch (vaultErr) {
      console.warn("Could not save routine output to vault:", vaultErr);
    }

    // Relay notification via WhatsApp if enabled
    notifyWhatsAppUser(
      `Routine Executed: ${routine.title}`,
      executionResult.content.slice(0, 300) + "...",
      {
        agentName: agent ? agent.displayName : "Scheduled Routine",
        status: "Completed & Ready in Review",
      }
    ).catch(() => {});
  }

  // 3. Update Routine state and calculate nextRunAt
  const nextRun = routine.type === "daily"
    ? calculateNextRun("daily", routine.time)
    : null;

  await prisma.routine.update({
    where: { id: routineId },
    data: {
      lastRunAt: new Date(),
      nextRunAt: nextRun,
      enabled: routine.type === "daily" ? routine.enabled : false,
    },
  });

  return {
    task,
    executionResult,
    nextRunAt: nextRun,
  };
}

/** Check and execute any due routines */
export async function checkAndRunDueRoutines() {
  const now = new Date();
  const dueRoutines = await prisma.routine.findMany({
    where: {
      enabled: true,
      nextRunAt: {
        lte: now,
      },
    },
  });

  const results = [];
  for (const r of dueRoutines) {
    try {
      const res = await executeRoutine(r.id);
      results.push({ routineId: r.id, success: true, ...res });
    } catch (err) {
      console.error(`Failed to execute due routine ${r.id}:`, err);
      results.push({
        routineId: r.id,
        success: false,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }

  return results;
}
